/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                    gridType?: components["schemas"]["GridType"];
                    sizePreset?: components["schemas"]["SizePreset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Map"];
                        "application/json": components["schemas"]["Map"];
                        "text/json": components["schemas"]["Map"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Worlds/{seed}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seed: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["World"];
                        "application/json": components["schemas"]["World"];
                        "text/json": components["schemas"]["World"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        Biome: "Forest" | "Desert" | "Tundra" | "Grassland" | "Swamp" | "Mountains" | "Ocean";
        Cell: {
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
            biome: components["schemas"]["Biome"];
            /** Format: double */
            elevation: number | string;
        };
        /** @enum {unknown} */
        GridType: "Square" | "Hex";
        Map: {
            /** Format: int32 */
            specVersion: number | string;
            seed: string;
            gridType: components["schemas"]["GridType"];
            sizePreset: components["schemas"]["SizePreset"];
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            cells: components["schemas"]["Cell"][];
        };
        /** @enum {unknown} */
        SizePreset: "Small" | "Medium" | "Large" | "Huge";
        World: {
            /** Format: int32 */
            specVersion: number | string;
            seed: string;
            size: components["schemas"]["WorldSize"];
            biome: components["schemas"]["Biome"];
        };
        /** @enum {unknown} */
        WorldSize: "Small" | "Medium" | "Large";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
