/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Compass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Compass"];
                        "application/json": components["schemas"]["Compass"];
                        "text/json": components["schemas"]["Compass"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                    x?: number | string;
                    y?: number | string;
                    width?: number | string;
                    height?: number | string;
                    step?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Map"];
                        "application/json": components["schemas"]["Map"];
                        "text/json": components["schemas"]["Map"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Planets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Planet"];
                        "application/json": components["schemas"]["Planet"];
                        "text/json": components["schemas"]["Planet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PointsOfInterest/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PointOfInterestCatalogResponse"];
                        "application/json": components["schemas"]["PointOfInterestCatalogResponse"];
                        "text/json": components["schemas"]["PointOfInterestCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PointsOfInterest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                    x?: number | string;
                    y?: number | string;
                    width?: number | string;
                    height?: number | string;
                    step?: number | string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PointsOfInterest"];
                        "application/json": components["schemas"]["PointsOfInterest"];
                        "text/json": components["schemas"]["PointsOfInterest"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                    x?: number | string;
                    y?: number | string;
                    width?: number | string;
                    height?: number | string;
                    step?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegionBoundaries"];
                        "application/json": components["schemas"]["RegionBoundaries"];
                        "text/json": components["schemas"]["RegionBoundaries"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    seed?: string;
                    planets?: string[];
                    belt?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlanetarySystem"];
                        "application/json": components["schemas"]["PlanetarySystem"];
                        "text/json": components["schemas"]["PlanetarySystem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AsteroidBelt: {
            /** Format: int32 */
            afterSlot: number | string;
            /** Format: double */
            width: number | string;
            color: string;
            /** Format: int32 */
            count: number | string;
            orbit: components["schemas"]["Orbit"];
        };
        AsteroidField: {
            /** Format: double */
            inner: number | string;
            /** Format: double */
            outer: number | string;
            color: string;
            /** Format: int32 */
            count: number | string;
        };
        Atmosphere: {
            color: string;
            /** Format: double */
            density: number | string;
            clouds: null | components["schemas"]["CloudLayer"];
        };
        /** @enum {unknown} */
        Biome: "Ocean" | "Beach" | "Desert" | "Grassland" | "Swamp" | "Tundra" | "Forest" | "Rainforest" | "Mountains" | "Snow";
        BoundaryPoint: {
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
        };
        Cell: {
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
            biome: components["schemas"]["Biome"];
        };
        CentralBody: {
            kind: components["schemas"]["CentralBodyKind"];
            /** Format: double */
            size: number | string;
            color: string;
            orbit: null | components["schemas"]["Orbit"];
        };
        /** @enum {unknown} */
        CentralBodyKind: "RedDwarf" | "Orange" | "Yellow" | "BlueGiant" | "WhiteDwarf" | "Pulsar" | "BlackHole";
        CloudLayer: {
            color: string;
            /** Format: double */
            coverage: number | string;
        };
        Compass: {
            seed: string;
            /** Format: double */
            bearingDegrees: number | string;
        };
        Map: {
            /** Format: int32 */
            specVersion: number | string;
            seed: string;
            /** Format: int32 */
            originX: number | string;
            /** Format: int32 */
            originY: number | string;
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            cells: components["schemas"]["Cell"][];
        };
        Moon: {
            /** Format: double */
            size: number | string;
            palette: string[];
            orbit: components["schemas"]["Orbit"];
        };
        Orbit: {
            /** Format: double */
            radius: number | string;
            /** Format: double */
            periodSeconds: number | string;
            /** Format: double */
            phaseDegrees: number | string;
            /** Format: double */
            inclinationDegrees: number | string;
        };
        /**
         * @default Anywhere
         * @enum {unknown}
         */
        Placement: "Anywhere" | "Coast" | "Cape" | "Islet" | "Lake" | "NearCoast" | "OpenSea" | "Waterside";
        Planet: {
            /** Format: int32 */
            specVersion: number | string;
            seed: string;
            name: string;
            type: components["schemas"]["PlanetType"];
            /** Format: double */
            radius: number | string;
            description: string;
            palette: string[];
            /** Format: uint32 */
            textureSeed: number | string;
            features: components["schemas"]["SurfaceFeature"][];
            atmosphere: null | components["schemas"]["Atmosphere"];
            rings: null | components["schemas"]["Rings"];
            asteroidField: null | components["schemas"]["AsteroidField"];
            moons: components["schemas"]["Moon"][];
            /** Format: double */
            rotationPeriodSeconds: number | string;
            /** Format: double */
            axialTiltDegrees: number | string;
        };
        PlanetarySystem: {
            /** Format: int32 */
            specVersion: number | string;
            seed: string;
            name: string;
            central: components["schemas"]["CentralBody"][];
            slots: components["schemas"]["PlanetSlot"][];
            belt: null | components["schemas"]["AsteroidBelt"];
        };
        PlanetSlot: {
            /** Format: int32 */
            index: number | string;
            planetSeed: string;
            planet: components["schemas"]["Planet"];
            orbit: components["schemas"]["Orbit"];
        };
        /** @enum {unknown} */
        PlanetType: "Rocky" | "Desert" | "Oceanic" | "Ice" | "Lava" | "Toxic" | "GasGiant";
        PoiCategory: {
            id: string;
            label: string;
        };
        PoiEntry: {
            id: string;
            label: string;
            description: string;
            category: string;
            kind: components["schemas"]["PoiKind"];
            rarity: components["schemas"]["Rarity"];
            biomes: components["schemas"]["Biome"][];
            placement?: components["schemas"]["Placement"];
            tier?: null | components["schemas"]["SettlementTier"];
            /** Format: int32 */
            weight?: number | string;
            enabled?: boolean;
        };
        /** @enum {unknown} */
        PoiKind: "Terrain" | "Anchor" | "Service" | "Singular";
        PointOfInterest: {
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
            category: string;
            type: string;
            role: components["schemas"]["PoiRole"];
            tier?: null | components["schemas"]["SettlementTier"];
        };
        PointOfInterestCatalogResponse: {
            categories: components["schemas"]["PoiCategory"][];
            entries: components["schemas"]["PoiEntry"][];
            settlements: components["schemas"]["SettlementSpec"][];
        };
        PointsOfInterest: {
            seed: string;
            /** Format: int32 */
            originX: number | string;
            /** Format: int32 */
            originY: number | string;
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            points: components["schemas"]["PointOfInterest"][];
        };
        /** @enum {unknown} */
        PoiRole: "Single" | "Anchor" | "Satellite";
        /** @enum {unknown} */
        Rarity: "Exceptional" | "Rare" | "Uncommon" | "Common";
        RegionBoundaries: {
            seed: string;
            /** Format: int32 */
            originX: number | string;
            /** Format: int32 */
            originY: number | string;
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            points: components["schemas"]["BoundaryPoint"][];
        };
        Rings: {
            /** Format: double */
            inner: number | string;
            /** Format: double */
            outer: number | string;
            color: string;
        };
        ServiceSlot: {
            id: string;
            /** Format: int32 */
            min: number | string;
            /** Format: int32 */
            max: number | string;
        };
        SettlementSpec: {
            tier: components["schemas"]["SettlementTier"];
            rarity: components["schemas"]["Rarity"];
            /** Format: int32 */
            radius: number | string;
            services: components["schemas"]["ServiceSlot"][];
            /** Format: int32 */
            weight?: number | string;
        };
        /** @enum {unknown} */
        SettlementTier: "Point" | "Small" | "Medium" | "Large" | "Huge" | null;
        SurfaceFeature: {
            kind: components["schemas"]["SurfaceFeatureKind"];
            /** Format: double */
            latitudeDegrees: number | string;
            /** Format: double */
            longitudeDegrees: number | string;
            /** Format: double */
            size: number | string;
            /** Format: int32 */
            colorIndex: number | string;
        };
        /** @enum {unknown} */
        SurfaceFeatureKind: "Crater" | "Ridge" | "Dunes" | "Canyon" | "Continent" | "PolarCap" | "Crack" | "LavaFlow" | "Volcano" | "Lake" | "Band" | "Storm";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
